app = "bladerunner-bot"  # замени на название твоего приложения в Fly.io

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  DB_PATH = "/mnt/data/data.db"
  RUN_MODE = "polling"

[mounts]
  source = "data"
  destination = "/mnt/data"

[experimental]
  auto_rollback = true
